[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opendataval"
authors = [
    {name = "Kevin Jiang", email = "kfj2112@columbia.edu"},
    {name = "Weixin Liang", email = "wxliang@cs.stanford.edu"},
    {name = "Yongchan Kwon", email = "yk3012@columbia.edu"},
]
description = "Transparent Data Valuation"
readme = "README.md"
requires-python = ">=3.9.0"
keywords = ["Data Valuation", "Data Centric", "Machine Learning"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
]
dependencies = [
    "matplotlib~=3.7",
    "pandas~=2.0",
    "numpy~=1.24",
    "scipy~=1.10",
    "scikit-learn~=1.2",
    "torch~=2.0.0",
    "tqdm~=4.64",
    "jupyterlab~=3.6.1",
    "notebook~=6.5.2",
    "opendatasets~=0.1.22",
    "transformers~=4.27",
    "torchvision~=0.15",
    "typer~=0.9"
]
dynamic = ["version"]

[project.scripts]
opendataval = "opendataval.__main__:cli"

[project.optional-dependencies]
dev = [
    "ruff~=0.0.2",
    "black~=22.10",
    "sphinx~=6.1",
    "pre-commit~=3.2",
    "pip-tools~=6.13.0"
]
test = [
    "pytest~=7.2.2",
    "pytest-cov~=4.0.0"
]

[tool.hatch]
packages = ["opendataval"]

[tool.hatch.version]
path = "opendataval/__init__.py"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.ruff]
select = ["E", "F", "I", "C90", "RUF"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403", "E501"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.isort]
known-first-party = ["opendataval"]
known-third-party = [
    "torch",
    "numpy",
    "scipy",
    "pandas",
    "sklearn",
    "matplotlib",
    "tqdm",
    "opendatasets",
    "transformers",
    "torchvision",
    "typer"
]

[tool.coverage.run]
source = ["opendataval"]
omit = ["opendataval/model/*", "opendataval/dataloader/datasets/*"]

[tool.pytest.ini_options]
testpaths = ["test"]