name: Bug Report
description: File a bug report
body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/opendataval/opendataval/issues).
      #### If urgent, please reach out to the maintainers directly through email.
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If you haven't done so already, please update all dependencies with the following lines
      ```sh
      python -m pip install pip-tools
      pip-sync requirements-extra.txt
      ```

      If relevant, add a minimal example so that we can reproduce the error by running the code. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports and unexpected behavior, etc. For example:

      ```python
      # All necessary imports at the beginning
      import torch

      # A succinct reproducing example trimmed down to the essential parts:
      t = torch.tensor([[1, 5], [1, 19]], device=torch.device("mps"))
      t.argmax()  # tensor(-9223372036854775808, device='mps:0'), expected 4
      ```

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
- type: textarea
  attributes:
    label: Versions
    description: |
      Please run the following to get the dependencies and paste below.
      ```sh
      pip-compile --resolver=backtracking --dry-run pyproject.toml
      ```
- type: dropdown
  id: version
  attributes:
    label: Operating System
    description: What Operating system are you finding this bug
    options:
      - MacOS
      - Linux
      - Windows
      - Other
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!