name: Make pre-release

on:
  workflow_dispatch:

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    outputs:
        tag_name: ${{ steps.tag.outputs.tag_name }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get tag data
        id: tag
        run: |
          # replace the following commands to use the new GITHUB_OUTPUT syntax
          # one day use github tags, for now just using source version
          echo tag_name=$(python -c "import opendataval; print(opendataval.__version__)") >> $GITHUB_OUTPUT

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "v${{ steps.tag.outputs.tag_name }}"
          draft: True
          title: "Version: ${{ steps.tag.outputs.tag_name }}"
          files: LICENSE.txt