name: Build and Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: setup.py
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install -e '.[dev, test]'
    - name: Lint with ruff
      run: |
        ruff dataoob/
        black --check dataoob/
    - name: Test with pytest
      run: |
        python -m pytest test/
