name: Build and Test

on: [pull_request]  # TODO Unfortunately, ran out of github action services this month

jobs:
  test:
    name: Runs Tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
      max-parallel: 5
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-dev.txt') }}
    - name: Install dependencies
      run: |
        make install-dev
    - name: Linting/formatting check
      run: |
        make format
    - name: Test with pytest
      run: |
        echo ${{ matrix.os }}
        echo ${{ matrix.python-version }}
        make test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      if: ${{(matrix.os == 'ubuntu-latest')  &&  (matrix.python-version == '3.11')}}
      with:
        name: code-coverage-report
        path: coverage.xml
        retention-days: 1
